services:

# services
  # webserver
  service_wallet_webserver:
    image: nginx:latest
    container_name: container_wallet_webserver
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - service_wallet_php_fpm
    networks:
      - network_wallet
    volumes:
      - type: bind
        source: ./backend/api-wallet
        target: /var/www/html/api-wallet
      - type: bind
        source: ./backend/nginx/conf.d/backend-api.conf
        target: /etc/nginx/conf.d/backend-api.conf
      - type: bind
        source: ./backend/soap-wallet
        target: /var/www/html/soap-wallet
      - type: bind
        source: ./backend/nginx/conf.d/backend-soap.conf
        target: /etc/nginx/conf.d/backend-soap.conf
      - type: bind
        source: ./backend/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
  service_wallet_php_fpm:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: php-fpm/wallet:v1
    container_name: container_wallet_php_fpm
    ports:
      - "9001:9001"
    networks:
      - network_wallet
    depends_on:
      - service_wallet_pgsql
    volumes:
      - type: bind
        source: ./backend/soap-wallet
        target: /var/www/html/soap-wallet
      - type: bind
        source: ./backend/api-wallet
        target: /var/www/html/api-wallet
      - type: bind
        source: ./backend/php-fpm/www.conf
        target: /usr/local/etc/php-fpm.d/www.conf
  # pgsql
  service_wallet_pgsql:
    image: postgres:latest
    container_name: container_wallet_pgsql
    networks:
      - network_wallet
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: user_wallet
      POSTGRES_PASSWORD: DP4d3XsPA2KQVhrAuaMJ8mh4SYuCmV1G
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

networks:
  network_wallet:

volumes:
  postgres_data:
